- hosts:
  - host01
  - host02
  - host03
  - host04
  - host05
  - host06
  - host07
  - host08
  - host09
  - host10
  gather_facts: yes
  serial: [1, 2, 3]
  tags: [a]
  tasks:
  - name: test foo
    debug:
      msg: "Here we are"
  - name: task two
    fail:
    when: 1 == 1

- hosts: localhost
  gather_facts: yes
  pre_tasks:
  - debug:
      msg: "Hi, I'm in the pre_tasks"
  tasks:
  - debug:
      msg: "task outside of a block"
  - name: block one
    block:
    - debug:
        msg: "test debug in block 1"
    rescue:
    - debug:
        msg: "test debug in rescue of block 1"
    always:
    - debug:
        msg: "test debug in always of block 1"
    delegate_to: otherhost
    tags: [a]
  - name: block two
    block:
    - debug:
        msg: "test debug in block 2 before nested block"
    - name: nested block
      block:
      - debug:
          msg: "debug in nested block"
      always:
      - debug:
          msg: "debug in always of nested block"
    - debug:
        msg: "debug after nested block"
    tags: [a]
  post_tasks:
  - debug:
      msg: "Bye, I'm in the post_tasks"

- hosts: localhost
  gather_facts: yes
  tasks:
  - ping:
  - name: some command
    command: "echo 'Hello'"
